/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LoginPage.module.css";

function Header() {
  const navItems = ["HOME", "PRODUCT", "ABOUT US", "CONTACT US", "LOGIN"];

  return (
    <header className={styles.header}>
      <nav className={styles.navigation}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c79b8763bb0a6cecd57576686d0b1a53f108100cd7dcc10f141d2862be493e31?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt="Company Logo"
          className={styles.logo}
        />
        <ul className={styles.navList}>
          {navItems.map((item, index) => (
            <li key={index} className={styles.navItem}>
              {item}
            </li>
          ))}
        </ul>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/33dbef9d6e4047ab39969cb4767a5c4a2cbb566c10a384b98d7f69739ae476ba?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt="Menu Icon"
          className={styles.menuIcon}
        />
      </nav>
    </header>
  );
}

export default Header;
