/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactInfo.module.css";

function ContactInfo() {
  const contactDetails = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/bd59e86ffde6117416123ed09486da2a6ec1085a14fea00c3e1bfdd3decb3067?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      label: "Phone",
      value: "+94 775849312",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/bd59e86ffde6117416123ed09486da2a6ec1085a14fea00c3e1bfdd3decb3067?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      label: "Email",
      value: "othisiclothing@gmail.com",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8cc3c6973df08376c7d15642e40cc6679a03b190a0b22318342ffe57e1e855bb?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      label: "Address",
      value: "23/5, High level road, Nugegoda.",
    },
  ];

  return (
    <div className={styles.contactInfo}>
      {contactDetails.map((detail, index) => (
        <div key={index} className={styles.infoItem}>
          <img src={detail.icon} alt="" className={styles.infoIcon} />
          <div className={styles.infoText}>
            <span className={styles.infoLabel}>{detail.label}</span>
            <span className={styles.infoValue}>{detail.value}</span>
          </div>
        </div>
      ))}
    </div>
  );
}

export default ContactInfo;
