/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactForm.module.css";

function ContactForm() {
  return (
    <form className={styles.contactForm}>
      <div className={styles.formField}>
        <label htmlFor="name" className={styles.formLabel}>
          Name :
        </label>
        <input type="text" id="name" className={styles.formInput} required />
      </div>
      <div className={styles.formField}>
        <label htmlFor="email" className={styles.formLabel}>
          Email :
        </label>
        <input type="email" id="email" className={styles.formInput} required />
      </div>
      <div className={styles.formField}>
        <label htmlFor="message" className={styles.formLabel}>
          Message :
        </label>
        <textarea
          id="message"
          className={styles.formTextarea}
          required
        ></textarea>
      </div>
      <button type="submit" className={styles.submitButton}>
        Send Message
      </button>
    </form>
  );
}

export default ContactForm;
