/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactUs.module.css";
import Header from "./Header";
import ContactForm from "./ContactForm";
import ContactInfo from "./ContactInfo";
import Footer from "./Footer";

function ContactUs() {
  return (
    <div className={styles.contactUsPage}>
      <header className={styles.pageHeader}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9e28fcbde39566245defaca41f6d93945a0669b4ecf711d2d0c8324fd7332be?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt=""
          className={styles.backgroundImage}
        />
        <div className={styles.headerContent}>
          <Header />
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed8413dcd605c106155cabb0c7de64815d557853f089a5c1710a2c014fdb60ea?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
            alt="Contact Us"
            className={styles.contactImage}
          />
          <h1 className={styles.pageTitle}>Contact us</h1>
        </div>
      </header>
      <main className={styles.mainContent}>
        <div className={styles.contentWrapper}>
          <section className={styles.contactSection}>
            <ContactForm />
            <ContactInfo />
          </section>
          <section className={styles.mapSection}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/37651279a47a3fc4a01435c96259bc6c63415ba76314d2361a855696899c3b83?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
              alt="Location map"
              className={styles.mapImage}
            />
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}

export default ContactUs;
