/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

function Footer() {
  return (
    <footer className={styles.siteFooter}>
      <div className={styles.footerContent}>
        <div className={styles.footerSection}>
          <h2 className={styles.sectionTitle}>About Us</h2>
          <p className={styles.sectionText}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec
            odio. Praesent libero. Sed cursus ante dapibus diam.
          </p>
        </div>
        <div className={styles.footerSection}>
          <h2 className={styles.sectionTitle}>Quick Links</h2>
          <ul className={styles.quickLinks}>
            <li>
              <a href="#home">Home</a>
            </li>
            <li>
              <a href="#about">About</a>
            </li>
            <li>
              <a href="#services">Services</a>
            </li>
            <li>
              <a href="#contact">Contact</a>
            </li>
          </ul>
        </div>
        <div className={styles.footerSection}>
          <h2 className={styles.sectionTitle}>Social Media</h2>
          <div className={styles.socialIcons}>
            <a href="#" aria-label="Facebook">
              <div className={styles.socialIcon}></div>
            </a>
            <a href="#" aria-label="Twitter">
              <div className={styles.socialIcon}></div>
            </a>
            <a href="#" aria-label="Instagram">
              <div className={styles.socialIcon}></div>
            </a>
          </div>
        </div>
        <div className={styles.footerSection}>
          <h2 className={styles.sectionTitle}>Contact Us</h2>
          <address className={styles.contactInfo}>
            Email: info@example.com
            <br />
            Phone: +123 456 7890
            <br />
            Address: 123 Street Name, City, Country
          </address>
        </div>
      </div>
      <div className={styles.footerDivider}></div>
      <div className={styles.copyright}>
        © 2024 Your Website. All Rights Reserved.
      </div>
    </footer>
  );
}

export default Footer;
