/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

function Header() {
  return (
    <header className={styles.header}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c79b8763bb0a6cecd57576686d0b1a53f108100cd7dcc10f141d2862be493e31?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
        alt="Company Logo"
        className={styles.logo}
      />
      <nav className={styles.navigation}>
        <a href="#home" className={styles.navLink}>
          HOME
        </a>
        <a href="#product" className={styles.navLink}>
          PRODUCT
        </a>
        <a href="#about" className={styles.navLink}>
          ABOUT US
        </a>
        <a href="#contact" className={styles.navLink}>
          CONTACT US
        </a>
        <a href="#login" className={styles.navLink}>
          LOGIN
        </a>
      </nav>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ff72c3dda0abc8e5d4de64e08c83a9c32889e86fd3fd4a3f13475cc368c4755?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
        alt="Menu Icon"
        className={styles.menuIcon}
      />
    </header>
  );
}

export default Header;
