/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./components/Thaiboxing/Thaiboxing.module.css";
import Header from "./components/Thaiboxing/Header";
import ProductCard from "./components/Thaiboxing/ProductCard";
import Footer from "./components/Thaiboxing/Footer";
import pi1 from "./components/Thaiboxing/photos/images (1).jpeg";
import pi3 from "./components/Thaiboxing/photos/images (3).jpeg";
import pi10 from "./components/Thaiboxing/photos/download.jpeg";
import pi11 from "./components/Thaiboxing/photos/download1.jpeg";

const products = [
  {
    id: 1,
    name: "Muay Thai ,blue-red | 10 Oz |8203",
    price: 13,
    image: pi10,
    rating: 4,
  },
  {
    id: 2,
    name: " Black and silver thai mongkol |UK",
    price: 20,
    image: pi3,
    rating: 5,
  },
  {
    id: 3,
    name: "Muay  thai short",
    price: 12,
    image: pi1,
    rating: 4,
  },
  {
    id: 4,
    name: "Muay thai  gloves",
    price: 10,
    image: pi11,
    rating: 5,
  },
];

const Thaiboxing = () => {
  return (
    <div className={styles.Thaiboxing}>
      <header className={styles.heroSection}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c7314c628367f71bb396c50492c55757e840947dd96acb173ed18fe4af3229c9?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt="Cricket field background"
          className={styles.heroBackground}
        />
        <Header />
        <div className={styles.heroContent}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed8413dcd605c106155cabb0c7de64815d557853f089a5c1710a2c014fdb60ea?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
            alt="Cricket player"
            className={styles.heroImage}
          />
          <form className={styles.searchForm}>
            <label htmlFor="searchInput" className={styles.visuallyHidden}>
              Search for Thaiboxing items
            </label>
            <input
              type="text"
              id="searchInput"
              placeholder="Search Thaiboxing items"
              className={styles.searchInput}
            />
            <button type="submit" className={styles.searchButton}>
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/728315a4dee7886052f73849805a080167688f2df94a767b1b67861977e91d84?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
                alt="Search"
                className={styles.searchIcon}
              />
            </button>
          </form>
        </div>
      </header>

      <main className={styles.mainContent}>
        <h1 className={styles.sectionTitle}>ThaiBoxing</h1>
        <section className={styles.productGrid}>
          {products.map((product) => (
            <ProductCard key={product.id} {...product} />
          ))}
        </section>

        <img
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeI863eP0UBYrdd0Ymc69qeVFzaWPKzGsU1g&s"
          alt="Cricket equipment banner"
          className={styles.bannerImage}
        />

        <section className={styles.additionalProducts}>
          <div className={styles.productRow}>
          <ProductCard
            name="Muay thai Rope"
            price={12}
            image="https://www.duogear.co.uk/cdn/shop/products/prajioud__2_redwhite_1200x.jpg?v=1654690216"
          />
            <ProductCard
              name="Muay thai low/leg kick pad"
              price={16}
              image="https://www.nakmuaywholesale.com/wp-content/uploads/2020/07/K-Muay-Thai-Equipment-Single-Strap-Kick-Pads-Blue.png"
            />
             <ProductCard
              name="Nak Muay nation double gloves"
              price={15}
              image="https://www.kanongwear.com/image/cache/data/202103-custom-gloves/KNGCUST-001-600x450.jpg"
            />
          </div>
          <aside className={styles.sideProduct}>
            <ProductCard
              name="Mauy Thai Boxing shoes"
              price={20}
              image="https://m.media-amazon.com/images/I/71or3VPRjaL._AC_UY900_.jpg"
            />
              </aside>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Thaiboxing;
