/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

const Header = () => {
  return (
    <header className={styles.header}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c7314c628367f71bb396c50492c55757e840947dd96acb173ed18fe4af3229c9?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
        alt="Rugby background"
        className={styles.backgroundImage}
      />
      <nav className={styles.navbar}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c79b8763bb0a6cecd57576686d0b1a53f108100cd7dcc10f141d2862be493e31?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt="Logo"
          className={styles.logo}
        />
        <ul className={styles.navLinks}>
          <li>
            <a href="#home">HOME</a>
          </li>
          <li>
            <a href="#product">PRODUCT</a>
          </li>
          <li>
            <a href="#about">ABOUT US</a>
          </li>
          <li>
            <a href="#contact">CONTACT US</a>
          </li>
          <li>
            <a href="#login">LOGIN</a>
          </li>
        </ul>
      </nav>
      <div className={styles.searchContainer}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed8413dcd605c106155cabb0c7de64815d557853f089a5c1710a2c014fdb60ea?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt="Rugby player"
          className={styles.playerImage}
        />
        <form className={styles.searchForm}>
          <label htmlFor="searchInput" className="visually-hidden">
            Search Rugby
          </label>
          <input
            type="search"
            id="searchInput"
            placeholder="Rugby"
            className={styles.searchInput}
          />
          <button type="submit" className={styles.searchButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/728315a4dee7886052f73849805a080167688f2df94a767b1b67861977e91d84?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
              alt="Search"
              className={styles.searchIcon}
            />
          </button>
        </form>
      </div>
    </header>
  );
};

export default Header;
